"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// `.env.ts` is generated by the `npm run env` command
var _env_1 = require("./.env");
exports.environment = {
    production: true,
    version: _env_1.default.npm_package_version,
    serverUrl: '/api',
    fakeServerUrl: 'http://127.0.0.1:3000/fakeapi',
    defaultLanguage: 'en-US',
    supportedLanguages: [
        'en-US',
        'en-Test'
    ]
};
//# sourceMappingURL=environment.prod.js.map